// ─── DOM REFERENCES & MUTABLE STATE ────────────────────────────────────────
let race = null;
let lastFrame = 0;
let evolutionModal = null;
let evolutionAnimationActive = false;
let verticalRace = null;
let pendingCutsceneStart = null;
let activeCutsceneLines = null;
let activeCutsceneIndex = 0;
let activeCutsceneContext = null;
let pendingDragRace = null;
let pendingIntroView = null;
let pendingPinkSlipContinue = null;
let upgradeModalCarId = null;
let selectedInventoryPartKey = partVariants[0]?.key || "";
let equipPartContext = null;
let pendingPinkSlipRiskStart = null;
const modeFlow = {
  drag: "car",
  time: "car",
  boss: "car",
  battle: "car",
  story: "car"
};
let battleState = null;
let expandedGarageCardIds = new Set();
const carPickerState = {
  target: "",
  highlighted: "",
  search: "",
  filters: {
    favorites: false,
    recent: false,
    ready: false,
    types: []
  },
  sort: "level-desc"
};
let pendingBondSceneQueue = [];
let activeBondScene = null;
let convoyLoadoutsReturnView = "convoy";
let storyReplayOpen = false;
const customTracksKey = "gearborn_custom_tracks";
const builderGridSize = 12;
let builderAllowLeave = false;
let pendingBuilderLeaveView = null;
const builderState = {
  mode: "menu",
  id: null,
  name: "Untitled Track",
  grid: [],
  selectedTile: "grass",
  rotation: 0,
  tool: "build",
  dirty: false,
  modalMode: null,
  pendingName: ""
};

const builderTileDefs = [
  { id: "grass", label: "Grass", asset: "assets/tracks/grass.png", accent: "transparent" },
  { id: "road_horizontal", label: "Horizontal Road", asset: "assets/tracks/track-horizontal.png", accent: "transparent", placeType: "road_straight", placeRotation: 0 },
  { id: "road_vertical", label: "Vertical Road", asset: "assets/tracks/track-vertical.png", accent: "transparent", placeType: "road_straight", placeRotation: 90 },
  { id: "road_turn", label: "Road Turn", asset: "assets/tracks/track-turn.png", accent: "transparent" },
  { id: "wall_straight", label: "Wall Straight", asset: "assets/tracks/wall_straight.png", accent: "transparent" },
  { id: "wall_corner", label: "Wall Corner", asset: "assets/tracks/wall_corner.png", accent: "transparent" },
  { id: "start_finish", label: "Start / Finish", asset: "assets/tracks/start-finish-line.png", accent: "transparent", marker: true },
  { id: "checkpoint", label: "Checkpoint", asset: "assets/tracks/checkpoint-neutral.png", accent: "transparent", marker: true }
];

const el = {
  views: document.querySelectorAll(".view"),
  navButtons: document.querySelectorAll("[data-view]"),
  sproxTotal: document.querySelector("#sprox-total"),
  dragCarGrid: document.querySelector("#drag-car-grid"),
  timeCarGrid: document.querySelector("#time-car-grid"),
  bossCarGrid: document.querySelector("#boss-car-grid"),
  battleCarGrid: document.querySelector("#battle-car-grid"),
  storyCarGrid: document.querySelector("#story-car-grid"),
  betaCarGrid: document.querySelector("#beta-car-grid"),
  dragCarSelectPreview: document.querySelector("#drag-car-select-preview"),
  timeCarSelectPreview: document.querySelector("#time-car-select-preview"),
  bossCarSelectPreview: document.querySelector("#boss-car-select-preview"),
  battleCarSelectPreview: document.querySelector("#battle-car-select-preview"),
  storyCarSelectPreview: document.querySelector("#story-car-select-preview"),
  betaCarSelectPreview: document.querySelector("#beta-car-select-preview"),
  betaCarSelectPanel: document.querySelector("#beta-car-select-panel"),
  betaCarSelectToggle: document.querySelector("#beta-car-select-toggle"),
  betaCarSelectOpen: document.querySelector("#beta-car-select-open"),
  betaCarSelectScreen: document.querySelector("#beta-car-select-screen"),
  betaCarSelectConfirm: document.querySelector("#beta-car-select-confirm"),
  betaCarSelectBack: document.querySelector("#beta-car-select-back"),
  betaMainScreen: document.querySelector("#beta-main-screen"),
  betaTrackSelectScreen: document.querySelector("#beta-track-select-screen"),
  betaTrackSelectTitle: document.querySelector("#beta-track-select-title"),
  betaPreviewScreen: document.querySelector("#beta-preview-screen"),
  betaPreviewBack: document.querySelector("#beta-preview-back"),
  betaPreviewTitle: document.querySelector("#beta-preview-title"),
  betaLeaderboard: document.querySelector("#beta-leaderboard"),
  betaPreviewMap: document.querySelector("#beta-preview-map"),
  betaPreviewCity: document.querySelector("#beta-preview-city"),
  betaCityMenu: document.querySelector("#beta-city-menu"),
  betaPreviewCar: document.querySelector("#beta-preview-car"),
  betaPreviewStart: document.querySelector("#beta-preview-start"),
  playerCar: document.querySelector("#player-car"),
  storyCar: document.querySelector("#story-car"),
  campaignCar: document.querySelector("#campaign-car"),
  timeCar: document.querySelector("#time-car"),
  timeTrack: document.querySelector("#time-track"),
  timeTrackGrid: document.querySelector("#time-track-grid"),
  timeTrackPreview: document.querySelector("#time-track-preview"),
  bossList: document.querySelector("#boss-list"),
  bossPreview: document.querySelector("#boss-preview"),
  battleList: document.querySelector("#battle-list"),
  battlePreview: document.querySelector("#battle-preview"),
  startBattle: document.querySelector("#start-battle"),
  battleArena: document.querySelector("#battle-arena"),
  battlePlayerName: document.querySelector("#battle-player-name"),
  battleOpponentName: document.querySelector("#battle-opponent-name"),
  battlePlayerHpFill: document.querySelector("#battle-player-hp-fill"),
  battleOpponentHpFill: document.querySelector("#battle-opponent-hp-fill"),
  battlePlayerHp: document.querySelector("#battle-player-hp"),
  battleOpponentHp: document.querySelector("#battle-opponent-hp"),
  battlePlayerSpFill: document.querySelector("#battle-player-sp-fill"),
  battleOpponentSpFill: document.querySelector("#battle-opponent-sp-fill"),
  battlePlayerSp: document.querySelector("#battle-player-sp"),
  battleOpponentSp: document.querySelector("#battle-opponent-sp"),
  battlePlayerCar: document.querySelector("#battle-player-car"),
  battleOpponentCar: document.querySelector("#battle-opponent-car"),
  battlePlayerMove: document.querySelector("#battle-player-move"),
  battleOpponentMove: document.querySelector("#battle-opponent-move"),
  battleActions: document.querySelector("#battle-actions"),
  battleNextTurn: document.querySelector("#battle-next-turn"),
  battleLog: document.querySelector("#battle-log"),
  startStory: document.querySelector("#start-story"),
  startTimeTrial: document.querySelector("#start-time-trial"),
  storyTrack: document.querySelector("#story-track"),
  timeTrialTrack: document.querySelector("#time-trial-track"),
  storyPlayer: document.querySelector("#story-player"),
  storyBoss: document.querySelector("#story-boss"),
  timePlayer: document.querySelector("#time-player"),
  timeGhost: document.querySelector("#time-ghost"),
  storyLocation: document.querySelector("#story-location"),
  storySpeed: document.querySelector("#story-speed"),
  storyDistance: document.querySelector("#story-distance"),
  storyCountdown: document.querySelector("#story-countdown"),
  storyMapStart: document.querySelector("#story-map-start"),
  storyMessage: document.querySelector("#story-message"),
  timeLocation: document.querySelector("#time-location"),
  timeClock: document.querySelector("#time-clock"),
  timeDistance: document.querySelector("#time-distance"),
  timeCountdown: document.querySelector("#time-countdown"),
  timeMapStart: document.querySelector("#time-map-start"),
  timeMessage: document.querySelector("#time-message"),
  timeTargets: document.querySelector("#time-targets"),
  betaIntro: document.querySelector("#beta-intro"),
  betaRace: document.querySelector("#beta-race"),
  betaOptions: document.querySelector("#beta-options"),
  betaMode: document.querySelector("#beta-mode"),
  beta3dRace: document.querySelector("#beta-3d-race"),
  beta3dStart: document.querySelector("#beta-3d-start"),
  beta3dCanvas: document.querySelector("#beta-3d-canvas"),
  beta3dExit: document.querySelector("#beta-3d-exit"),
  beta3dFinishExit: document.querySelector("#beta-3d-finish-exit"),
  beta3dRestart: document.querySelector("#beta-3d-restart"),
  beta3dResults: document.querySelector("#beta-3d-results"),
  beta3dFinalTime: document.querySelector("#beta-3d-final-time"),
  beta3dTime: document.querySelector("#beta-3d-time"),
  beta3dSpeed: document.querySelector("#beta-3d-speed"),
  beta3dProgressFill: document.querySelector("#beta-3d-progress-fill"),
  beta3dMarker: document.querySelector("#beta-3d-marker"),
  betaTrackSelect: document.querySelector("#beta-track-select"),
  betaTrackList: document.querySelector("#beta-track-list"),
  betaTrackPreview: document.querySelector("#beta-track-preview"),
  betaTrackStart: document.querySelector("#beta-track-start"),
  betaTrackBack: document.querySelector("#beta-track-back"),
  betaLoading: document.querySelector("#beta-loading"),
  betaExit: document.querySelector("#beta-exit"),
  betaFinishExit: document.querySelector("#beta-finish-exit"),
  betaRestart: document.querySelector("#beta-restart"),
  betaDebug: document.querySelector("#beta-debug"),
  betaCanvas: document.querySelector("#beta-canvas"),
  betaMinimap: document.querySelector("#beta-minimap"),
  betaTime: document.querySelector("#beta-time"),
  betaLap: document.querySelector("#beta-lap"),
  betaCheckpoint: document.querySelector("#beta-checkpoint"),
  betaSpeed: document.querySelector("#beta-speed"),
  betaPosition: document.querySelector("#beta-position"),
  betaItemSlot: document.querySelector("#beta-item-slot"),
  betaItemIcon: document.querySelector("#beta-item-icon"),
  betaItemName: document.querySelector("#beta-item-name"),
  betaItemPrompt: document.querySelector("#beta-item-prompt"),
  betaCountdown: document.querySelector("#beta-countdown"),
  betaResults: document.querySelector("#beta-results"),
  betaFinalTime: document.querySelector("#beta-final-time"),
  garageLoadoutsOpen: document.querySelector("#garage-loadouts-open"),
  builderMenu: document.querySelector("#builder-menu"),
  builderEditor: document.querySelector("#builder-editor"),
  builderLoadPanel: document.querySelector("#builder-load-panel"),
  builderNew: document.querySelector("#builder-new"),
  builderLoad: document.querySelector("#builder-load"),
  builderMenuNote: document.querySelector("#builder-menu-note"),
  builderPalette: document.querySelector("#builder-palette"),
  builderGrid: document.querySelector("#builder-grid"),
  builderCurrentName: document.querySelector("#builder-current-name"),
  builderDirtyState: document.querySelector("#builder-dirty-state"),
  builderBuild: document.querySelector("#builder-build"),
  builderRotate: document.querySelector("#builder-rotate"),
  builderClear: document.querySelector("#builder-clear"),
  builderSave: document.querySelector("#builder-save"),
  builderExit: document.querySelector("#builder-exit"),
  builderLoadBack: document.querySelector("#builder-load-back"),
  builderTrackList: document.querySelector("#builder-track-list"),
  deleteTracks: document.querySelector("#delete-tracks"),
  builderModal: document.querySelector("#builder-modal"),
  builderModalTitle: document.querySelector("#builder-modal-title"),
  builderModalCopy: document.querySelector("#builder-modal-copy"),
  builderModalSubcopy: document.querySelector("#builder-modal-subcopy"),
  builderModalInput: document.querySelector("#builder-modal-input"),
  builderModalActions: document.querySelector("#builder-modal-actions"),
  campaignList: document.querySelector("#campaign-list"),
  storyCityMap: document.querySelector("#story-city-map"),
  tunerRankBadge: document.querySelector("#tuner-rank-badge"),
  tunerRankOpen: document.querySelector("#tuner-rank-open"),
  tunerRankList: document.querySelector("#tuner-rank-list"),
  tunerRankBack: document.querySelector("#tuner-rank-back"),
  convoyEntryNode: document.querySelector("#convoy-entry-node"),
  convoyButtons: document.querySelector("#convoy-buttons"),
  convoyTitle: document.querySelector("#convoy-title"),
  convoySummary: document.querySelector("#convoy-summary"),
  convoyStageList: document.querySelector("#convoy-stage-list"),
  convoyBack: document.querySelector("#convoy-back"),
  convoyLoadoutsOpen: document.querySelector("#convoy-loadouts-open"),
  convoyLoadoutsView: document.querySelector("#convoy-loadouts-view"),
  convoyLoadoutSlots: document.querySelector("#convoy-loadout-slots"),
  convoyLoadoutsBack: document.querySelector("#convoy-loadouts-back"),
  storyCitySelect: document.querySelector("#story-city-select"),
  changeStoryCar: document.querySelector("#change-story-car"),
  storyCityIcon: document.querySelector("#story-city-icon"),
  storyCityTitle: document.querySelector("#story-city-title"),
  storyCitySelect: document.querySelector("#story-city-select"),
  bossUnlockNote: document.querySelector("#boss-unlock-note"),
  storyMapStage: document.querySelector("#story-map-stage"),
  storyPreviewPanel: document.querySelector("#story-preview-panel"),
  closeStoryPreview: document.querySelector("#close-story-preview"),
  storyPreviewIcon: document.querySelector("#story-preview-icon"),
  storyPreviewArt: document.querySelector("#story-preview-art"),
  storyPreviewLeaderboard: document.querySelector("#story-preview-leaderboard"),
  storyCitySelectPanel: document.querySelector("#story-city-select-panel"),
  closeCitySelect: document.querySelector("#close-city-select"),
  storyCityGrid: document.querySelector("#story-city-grid"),
  campaignType: document.querySelector("#campaign-type"),
  campaignTitle: document.querySelector("#campaign-title"),
  campaignMeta: document.querySelector("#campaign-meta"),
  campaignRewards: document.querySelector("#campaign-rewards"),
  storyLoadout: document.querySelector("#story-loadout"),
  startCampaign: document.querySelector("#start-campaign"),
  changeStoryCar: document.querySelector("#change-story-car"),
  replayCampaign: document.querySelector("#replay-campaign"),
  campaignRaceMount: document.querySelector("#campaign-race-mount"),
  vindexList: document.querySelector("#vindex-list"),
  vindexArt: document.querySelector("#vindex-art"),
  vindexNumber: document.querySelector("#vindex-number"),
  vindexName: document.querySelector("#vindex-name"),
  vindexLine: document.querySelector("#vindex-line"),
  vindexStatus: document.querySelector("#vindex-status"),
  vindexClassStamp: document.querySelector("#vindex-class-stamp"),
  vindexTypeStamp: document.querySelector("#vindex-type-stamp"),
  vindexPlate: document.querySelector("#vindex-plate"),
  vindexFilterButtons: document.querySelector("#vindex-filter-buttons"),
  vindexProgress: document.querySelector("#vindex-progress"),
  vindexMemoriesButton: document.querySelector("#vindex-memories-button"),
  vindexMemoriesPanel: document.querySelector("#vindex-memories-panel"),
  bondSceneModal: document.querySelector("#bond-scene-modal"),
  bondScenePortrait: document.querySelector("#bond-scene-portrait"),
  bondSceneTitle: document.querySelector("#bond-scene-title"),
  bondSceneText: document.querySelector("#bond-scene-text"),
  bondSceneContinue: document.querySelector("#bond-scene-continue"),
  carPickerModal: document.querySelector("#car-picker-modal"),
  carPickerClose: document.querySelector("#car-picker-close"),
  carPickerSearch: document.querySelector("#car-picker-search"),
  carPickerFilters: document.querySelector("#car-picker-filters"),
  carPickerSort: document.querySelector("#car-picker-sort"),
  carPickerGrid: document.querySelector("#car-picker-grid"),
  carPickerSummary: document.querySelector("#car-picker-summary"),
  carPickerConfirm: document.querySelector("#car-picker-confirm"),
  profileList: document.querySelector("#profile-list"),
  profileArt: document.querySelector("#profile-art"),
  profileCarArt: document.querySelector("#profile-car-art"),
  profileName: document.querySelector("#profile-name"),
  profileMeta: document.querySelector("#profile-meta"),
  profileBio: document.querySelector("#profile-bio"),
  achievementList: document.querySelector("#achievement-list"),
  achievementDetail: document.querySelector("#achievement-detail"),
  playerPreviewArt: document.querySelector("#player-preview-art"),
  playerPreviewName: document.querySelector("#player-preview-name"),
  playerPreviewMeta: document.querySelector("#player-preview-meta"),
  distanceOptions: document.querySelector("#distance-options"),
  opponentList: document.querySelector("#opponent-list"),
  opponentPreviewArt: document.querySelector("#opponent-preview-art"),
  opponentPreviewName: document.querySelector("#opponent-preview-name"),
  opponentPreviewMeta: document.querySelector("#opponent-preview-meta"),
  startRace: document.querySelector("#start-race"),
  dragTrack: document.querySelector(".track"),
  dragMapStart: document.querySelector("#drag-map-start"),
  dragCountdown: document.querySelector("#drag-countdown"),
  godMode: document.querySelector("#god-mode"),
  godModal: document.querySelector("#god-modal"),
  godCode: document.querySelector("#god-code"),
  godCodeError: document.querySelector("#god-code-error"),
  confirmGod: document.querySelector("#confirm-god"),
  cancelGod: document.querySelector("#cancel-god"),
  upgradeModal: document.querySelector("#upgrade-modal"),
  closeUpgrade: document.querySelector("#close-upgrade"),
  confirmUpgrade: document.querySelector("#confirm-upgrade"),
  upgradeArt: document.querySelector("#upgrade-art"),
  upgradeSproxTotal: document.querySelector("#upgrade-sprox-total"),
  upgradeTitle: document.querySelector("#upgrade-title"),
  upgradeCarName: document.querySelector("#upgrade-car-name"),
  upgradeCarMeta: document.querySelector("#upgrade-car-meta"),
  upgradeStats: document.querySelector("#upgrade-stats"),
  upgradePartSlots: document.querySelector("#upgrade-part-slots"),
  upgradeCost: document.querySelector("#upgrade-cost"),
  openInventory: document.querySelector("#open-inventory"),
  inventoryModal: document.querySelector("#inventory-modal"),
  closeInventory: document.querySelector("#close-inventory"),
  partsGrid: document.querySelector("#parts-grid"),
  partDetail: document.querySelector("#part-detail"),
  equipPartModal: document.querySelector("#equip-part-modal"),
  closeEquipPart: document.querySelector("#close-equip-part"),
  equipPartsGrid: document.querySelector("#equip-parts-grid"),
  equipPartDetail: document.querySelector("#equip-part-detail"),
  confirmEquipPart: document.querySelector("#confirm-equip-part"),
  unequipPart: document.querySelector("#unequip-part"),
  replacePart: document.querySelector("#replace-part"),
  resetProgress: document.querySelector("#reset-progress"),
  replayTutorial: document.querySelector("#replay-tutorial"),
  tutorialReplayModal: document.querySelector("#tutorial-replay-modal"),
  tutorialReplayYes: document.querySelector("#tutorial-replay-yes"),
  tutorialSceneSelect: document.querySelector("#tutorial-scene-select"),
  tutorialReplayCancel: document.querySelector("#tutorial-replay-cancel"),
  tutorialSceneOptions: document.querySelector("#tutorial-scene-options"),
  tutorialFirstModal: document.querySelector("#tutorial-first-modal"),
  tutorialFirstYes: document.querySelector("#tutorial-first-yes"),
  tutorialFirstNo: document.querySelector("#tutorial-first-no"),
  cityUnlockModal: document.querySelector("#city-unlock-modal"),
  cityUnlockIcon: document.querySelector("#city-unlock-icon"),
  cityUnlockTitle: document.querySelector("#city-unlock-title"),
  cityUnlockClose: document.querySelector("#city-unlock-close"),
  pinkSlipWarningModal: document.querySelector("#pink-slip-warning-modal"),
  pinkSlipWarningCopy: document.querySelector("#pink-slip-warning-copy"),
  confirmPinkSlipRisk: document.querySelector("#confirm-pink-slip-risk"),
  cancelPinkSlipRisk: document.querySelector("#cancel-pink-slip-risk"),
  resetModal: document.querySelector("#reset-modal"),
  confirmReset: document.querySelector("#confirm-reset"),
  cancelReset: document.querySelector("#cancel-reset"),
  mph: document.querySelector("#mph"),
  gear: document.querySelector("#gear"),
  distance: document.querySelector("#distance"),
  shiftReadout: document.querySelector("#shift-readout"),
  tachFill: document.querySelector("#tach-fill"),
  playerRacer: document.querySelector("#player-racer"),
  playerRacerImage: document.querySelector("#player-racer-image"),
  rivalRacer: document.querySelector("#rival-racer"),
  rivalRacerImage: document.querySelector("#rival-racer-image"),
  raceMessage: document.querySelector("#race-message"),
  shiftButton: document.querySelector("#shift-button"),
  dragOpponentCount: document.querySelector("#drag-opponent-count"),
  dragLaneUp: document.querySelector("#drag-lane-up"),
  dragLaneDown: document.querySelector("#drag-lane-down"),
  gearshiftIndicator: document.querySelector("#gearshift-indicator"),
  dragLaunchLights: document.querySelector("#drag-launch-lights"),
  dragExtraOpponents: document.querySelector("#drag-extra-opponents"),
  rivalDragLane: document.querySelector("#rival-drag-lane"),
  playerDragLane: document.querySelector("#player-drag-lane"),
  nitroFill: document.querySelector("#nitro-fill"),
  nitroReadout: document.querySelector("#nitro-readout"),
  nitroButton: document.querySelector("#nitro-button"),
  garageGrid: document.querySelector("#garage-grid"),
  garageStatus: document.querySelector("#garage-status"),
  difficulty: document.querySelector("#difficulty"),
  volume: document.querySelector("#volume"),
  shiftKey: document.querySelector("#shift-key"),
  nitroKey: document.querySelector("#nitro-key"),
  verticalUpKey: document.querySelector("#vertical-up-key"),
  verticalDownKey: document.querySelector("#vertical-down-key"),
  verticalLeftKey: document.querySelector("#vertical-left-key"),
  verticalRightKey: document.querySelector("#vertical-right-key"),
  evolutionModal: document.querySelector("#evolution-modal"),
  forgePanel: document.querySelector("#forge-panel"),
  garageContent: document.querySelector("#garage-content"),
  forgeVatImg: document.querySelector("#forge-vat-img"),
  forgeMedallionGrid: document.querySelector("#forge-medallion-grid"),
  forgeInventoryPanel: document.querySelector("#forge-inventory-panel"),
  forgeAnimationArea: document.querySelector("#forge-animation-area"),
  forgeSelectedName: document.querySelector("#forge-selected-name"),
  forgeSelectedMedallion: document.querySelector("#forge-selected-medallion"),
  forgeUnlockBtn: document.querySelector("#forge-unlock-btn"),
  forgeUnlockedPopup: document.querySelector("#forge-unlocked-popup"),
  medallionEarnedPopup: document.querySelector("#medallion-earned-popup"),
  evolutionStage: document.querySelector("#evolution-stage"),
  evolutionKicker: document.querySelector("#evolution-kicker"),
  evolutionTitle: document.querySelector("#evolution-title"),
  evolutionCopy: document.querySelector("#evolution-copy"),
  evolveButton: document.querySelector("#evolve-button"),
  closeEvolution: document.querySelector("#close-evolution"),
  evolutionAnimation: document.querySelector("#evolution-animation"),
  evolutionAnimationCurrent: document.querySelector("#evolution-animation-current"),
  evolutionAnimationNext: document.querySelector("#evolution-animation-next"),
  bossModal: document.querySelector("#boss-modal"),
  bossPortrait: document.querySelector("#boss-portrait"),
  bossModalTitle: document.querySelector("#boss-modal-title"),
  bossModalKicker: document.querySelector("#boss-modal-kicker"),
  bossModalCopy: document.querySelector("#boss-modal-copy"),
  continueBoss: document.querySelector("#continue-boss"),
  closeBoss: document.querySelector("#close-boss"),
  tunerModal: document.querySelector("#tuner-modal"),
  tunerOptions: document.querySelector("#tuner-options"),
  settingsTunerOptions: document.querySelector("#settings-tuner-options"),
  cutsceneModal: document.querySelector("#cutscene-modal"),
  cutsceneTitle: document.querySelector("#cutscene-title"),
  cutsceneLeftArt: document.querySelector("#cutscene-left-art"),
  cutsceneRightArt: document.querySelector("#cutscene-right-art"),
  cutsceneLeftDialogue: document.querySelector("#cutscene-left-dialogue"),
  cutsceneRightDialogue: document.querySelector("#cutscene-right-dialogue"),
  backCutscene: document.querySelector("#back-cutscene"),
  continueCutscene: document.querySelector("#continue-cutscene"),
  skipCutscene: document.querySelector("#skip-cutscene"),
  closeCutscene: document.querySelector("#close-cutscene"),
  tutorialOverlay: document.querySelector("#tutorial-overlay"),
  tutorialCard: document.querySelector("#tutorial-card"),
  tutorialPortrait: document.querySelector("#tutorial-portrait"),
  tutorialKicker: document.querySelector("#tutorial-kicker"),
  tutorialTitle: document.querySelector("#tutorial-title"),
  tutorialCopy: document.querySelector("#tutorial-copy"),
  tutorialChoices: document.querySelector("#tutorial-choices"),
  tutorialBack: document.querySelector("#tutorial-back"),
  tutorialNext: document.querySelector("#tutorial-next"),
  tutorialSkip: document.querySelector("#tutorial-skip"),
  tutorialSkipModal: document.querySelector("#tutorial-skip-modal"),
  cancelTutorialSkip: document.querySelector("#cancel-tutorial-skip"),
  confirmTutorialSkip: document.querySelector("#confirm-tutorial-skip"),
  unmaskModal: document.querySelector("#unmask-modal"),
  unmaskPortrait: document.querySelector("#unmask-portrait"),
  unmaskButton: document.querySelector("#unmask-button"),
  continueUnmask: document.querySelector("#continue-unmask"),
  unmaskCopy: document.querySelector("#unmask-copy")
};
const embeddedRaceHomes = ["play", "time-trial", "boss", "battle"].map((view) => {
  const node = document.querySelector(`#${view}-view`);
  return { view, node, parent: node.parentNode, next: node.nextSibling };
});
let embeddedCampaignView = null;
let pendingBossRaceStart = null;
let pendingCityUnlock = null;
let pendingCityWelcome = null;
