// ─── DOM REFERENCES & MUTABLE STATE ────────────────────────────────────────
let race = null;
let lastFrame = 0;
let evolutionModal = null;
let evolutionAnimationActive = false;
let verticalRace = null;
let pendingCutsceneStart = null;
let activeCutsceneLines = null;
let activeCutsceneIndex = 0;
let activeCutsceneContext = null;
let pendingDragRace = null;
let pendingIntroView = null;
let pendingPinkSlipContinue = null;
let upgradeModalCarId = null;
let selectedInventoryPartKey = partVariants[0]?.key || "";
let equipPartContext = null;
let pendingPinkSlipRiskStart = null;
const modeFlow = {
  drag: "car",
  time: "car",
  boss: "car",
  battle: "car",
  story: "car"
};
let battleState = null;
let expandedGarageCardIds = new Set();
const carPickerState = {
  target: "",
  highlighted: "",
  search: "",
  filters: {
    favorites: false,
    recent: false,
    ready: false,
    types: []
  },
  sort: "level-desc"
};
let pendingBondSceneQueue = [];
let activeBondScene = null;
let convoyLoadoutsReturnView = "convoy";
let storyReplayOpen = false;
const customTracksKey = "gearborn_custom_tracks";
const builderGridSize = 12;
let builderAllowLeave = false;
let pendingBuilderLeaveView = null;
const builderState = {
  mode: "menu",
  id: null,
  name: "Untitled Track",
  grid: [],
  selectedTile: "grass",
  rotation: 0,
  tool: "build",
  dirty: false,
  modalMode: null,
  pendingName: ""
};

const builderTileDefs = [
  { id: "grass", label: "Grass", asset: "assets/tracks/grass.png", accent: "transparent" },
  { id: "road_horizontal", label: "Horizontal Road", asset: "assets/tracks/track-horizontal.png", accent: "transparent", placeType: "road_straight", placeRotation: 0 },
  { id: "road_vertical", label: "Vertical Road", asset: "assets/tracks/track-vertical.png", accent: "transparent", placeType: "road_straight", placeRotation: 90 },
  { id: "road_turn", label: "Road Turn", asset: "assets/tracks/track-turn.png", accent: "transparent" },
  { id: "wall_straight", label: "Wall Straight", asset: "assets/tracks/wall_straight.png", accent: "transparent" },
  { id: "wall_corner", label: "Wall Corner", asset: "assets/tracks/wall_corner.png", accent: "transparent" },
  { id: "start_finish", label: "Start / Finish", asset: "assets/tracks/start-finish-line.png", accent: "transparent", marker: true },
  { id: "checkpoint", label: "Checkpoint", asset: "assets/tracks/checkpoint-neutral.png", accent: "transparent", marker: true }
];

function queryEl(key, selector) {
  const node = document.querySelector(selector);
  if (!node) {
    const error = new Error(`Missing DOM reference: el.${key} (${selector})`);
    console.error(error.message);
    window.reportGearbornStartupError?.(error);
  }
  return node;
}

const el = {
  views: document.querySelectorAll(".view"),
  navButtons: document.querySelectorAll("[data-view]"),
  rotationTip: queryEl("rotationTip", "#rotation-tip"),
  rotationTipDismiss: queryEl("rotationTipDismiss", "#rotation-tip-dismiss"),
  sproxTotal: queryEl("sproxTotal", "#sprox-total"),
  spinTotal: queryEl("spinTotal", "#spin-total"),
  gasTank: queryEl("gasTank", "#gas-tank"),
  gasFill: queryEl("gasFill", "#gas-fill"),
  gasTotal: queryEl("gasTotal", "#gas-total"),
  gasNext: queryEl("gasNext", "#gas-next"),
  crankVaultBadge: queryEl("crankVaultBadge", "#crankvault-badge"),
  crankVaultDaily: queryEl("crankVaultDaily", "#crankvault-daily"),
  crankVaultStore: queryEl("crankVaultStore", "#crankvault-store"),
  crankVaultOddsNote: queryEl("crankVaultOddsNote", "#crankvault-odds-note"),
  crankVaultInventory: queryEl("crankVaultInventory", "#crankvault-inventory"),
  crankVaultInventoryTitle: queryEl("crankVaultInventoryTitle", "#crankvault-inventory-title"),
  crankVaultRevealModal: queryEl("crankVaultRevealModal", "#crankvault-reveal-modal"),
  crankVaultRevealTitle: queryEl("crankVaultRevealTitle", "#crankvault-reveal-title"),
  crankVaultRevealHero: queryEl("crankVaultRevealHero", "#crankvault-reveal-hero"),
  crankVaultRevealResults: queryEl("crankVaultRevealResults", "#crankvault-reveal-results"),
  crankVaultRevealClose: queryEl("crankVaultRevealClose", "#crankvault-reveal-close"),
  menuUnlockMarkers: queryEl("menuUnlockMarkers", "#menu-unlock-markers"),
  dragCarGrid: queryEl("dragCarGrid", "#drag-car-grid"),
  timeCarGrid: queryEl("timeCarGrid", "#time-car-grid"),
  bossCarGrid: queryEl("bossCarGrid", "#boss-car-grid"),
  battleCarGrid: queryEl("battleCarGrid", "#battle-car-grid"),
  storyCarGrid: queryEl("storyCarGrid", "#story-car-grid"),
  betaCarGrid: queryEl("betaCarGrid", "#beta-car-grid"),
  dragCarSelectPreview: queryEl("dragCarSelectPreview", "#drag-car-select-preview"),
  timeCarSelectPreview: queryEl("timeCarSelectPreview", "#time-car-select-preview"),
  bossCarSelectPreview: queryEl("bossCarSelectPreview", "#boss-car-select-preview"),
  battleCarSelectPreview: queryEl("battleCarSelectPreview", "#battle-car-select-preview"),
  storyCarSelectPreview: queryEl("storyCarSelectPreview", "#story-car-select-preview"),
  betaCarSelectPreview: queryEl("betaCarSelectPreview", "#beta-car-select-preview"),
  betaCarSelectPanel: queryEl("betaCarSelectPanel", "#beta-car-select-panel"),
  betaCarSelectToggle: queryEl("betaCarSelectToggle", "#beta-car-select-toggle"),
  betaCarSelectScreen: queryEl("betaCarSelectScreen", "#beta-car-select-screen"),
  betaCarSelectConfirm: queryEl("betaCarSelectConfirm", "#beta-car-select-confirm"),
  betaCarSelectBack: queryEl("betaCarSelectBack", "#beta-car-select-back"),
  betaTrackSelectScreen: queryEl("betaTrackSelectScreen", "#beta-track-select-screen"),
  betaTrackSelectTitle: queryEl("betaTrackSelectTitle", "#beta-track-select-title"),
  betaPreviewScreen: queryEl("betaPreviewScreen", "#beta-preview-screen"),
  betaPreviewBack: queryEl("betaPreviewBack", "#beta-preview-back"),
  betaPreviewTitle: queryEl("betaPreviewTitle", "#beta-preview-title"),
  betaLeaderboard: queryEl("betaLeaderboard", "#beta-leaderboard"),
  betaPreviewMap: queryEl("betaPreviewMap", "#beta-preview-map"),
  betaPreviewCity: queryEl("betaPreviewCity", "#beta-preview-city"),
  betaCityMenu: queryEl("betaCityMenu", "#beta-city-menu"),
  betaPreviewStart: queryEl("betaPreviewStart", "#beta-preview-start"),
  playerCar: queryEl("playerCar", "#player-car"),
  storyCar: queryEl("storyCar", "#story-car"),
  timeCar: queryEl("timeCar", "#time-car"),
  timeTrack: queryEl("timeTrack", "#time-track"),
  timeTrackGrid: queryEl("timeTrackGrid", "#time-track-grid"),
  timeTrackPreview: queryEl("timeTrackPreview", "#time-track-preview"),
  bossList: queryEl("bossList", "#boss-list"),
  bossPreview: queryEl("bossPreview", "#boss-preview"),
  battleList: queryEl("battleList", "#battle-list"),
  battlePreview: queryEl("battlePreview", "#battle-preview"),
  startBattle: queryEl("startBattle", "#start-battle"),
  battleArena: queryEl("battleArena", "#battle-arena"),
  battlePlayerName: queryEl("battlePlayerName", "#battle-player-name"),
  battleOpponentName: queryEl("battleOpponentName", "#battle-opponent-name"),
  battlePlayerHpFill: queryEl("battlePlayerHpFill", "#battle-player-hp-fill"),
  battleOpponentHpFill: queryEl("battleOpponentHpFill", "#battle-opponent-hp-fill"),
  battlePlayerHp: queryEl("battlePlayerHp", "#battle-player-hp"),
  battleOpponentHp: queryEl("battleOpponentHp", "#battle-opponent-hp"),
  battlePlayerSpFill: queryEl("battlePlayerSpFill", "#battle-player-sp-fill"),
  battleOpponentSpFill: queryEl("battleOpponentSpFill", "#battle-opponent-sp-fill"),
  battlePlayerSp: queryEl("battlePlayerSp", "#battle-player-sp"),
  battleOpponentSp: queryEl("battleOpponentSp", "#battle-opponent-sp"),
  battlePlayerCar: queryEl("battlePlayerCar", "#battle-player-car"),
  battleOpponentCar: queryEl("battleOpponentCar", "#battle-opponent-car"),
  battlePlayerMove: queryEl("battlePlayerMove", "#battle-player-move"),
  battleOpponentMove: queryEl("battleOpponentMove", "#battle-opponent-move"),
  battleActions: queryEl("battleActions", "#battle-actions"),
  battleNextTurn: queryEl("battleNextTurn", "#battle-next-turn"),
  battleLog: queryEl("battleLog", "#battle-log"),
  startStory: queryEl("startStory", "#start-story"),
  startTimeTrial: queryEl("startTimeTrial", "#start-time-trial"),
  storyTrack: queryEl("storyTrack", "#story-track"),
  timeTrialTrack: queryEl("timeTrialTrack", "#time-trial-track"),
  storyPlayer: queryEl("storyPlayer", "#story-player"),
  storyBoss: queryEl("storyBoss", "#story-boss"),
  timePlayer: queryEl("timePlayer", "#time-player"),
  timeGhost: queryEl("timeGhost", "#time-ghost"),
  storyLocation: queryEl("storyLocation", "#story-location"),
  storySpeed: queryEl("storySpeed", "#story-speed"),
  storyDistance: queryEl("storyDistance", "#story-distance"),
  storyCountdown: queryEl("storyCountdown", "#story-countdown"),
  storyMapStart: queryEl("storyMapStart", "#story-map-start"),
  storyMessage: queryEl("storyMessage", "#story-message"),
  timeLocation: queryEl("timeLocation", "#time-location"),
  timeClock: queryEl("timeClock", "#time-clock"),
  timeDistance: queryEl("timeDistance", "#time-distance"),
  timeCountdown: queryEl("timeCountdown", "#time-countdown"),
  timeMapStart: queryEl("timeMapStart", "#time-map-start"),
  timeMessage: queryEl("timeMessage", "#time-message"),
  timeTargets: queryEl("timeTargets", "#time-targets"),
  betaIntro: queryEl("betaIntro", "#beta-intro"),
  betaRace: queryEl("betaRace", "#beta-race"),
  betaOptions: queryEl("betaOptions", "#beta-options"),
  betaMode: queryEl("betaMode", "#beta-mode"),
  beta3dRace: queryEl("beta3dRace", "#beta-3d-race"),
  beta3dStart: queryEl("beta3dStart", "#beta-3d-start"),
  beta3dCanvas: queryEl("beta3dCanvas", "#beta-3d-canvas"),
  beta3dExit: queryEl("beta3dExit", "#beta-3d-exit"),
  beta3dFinishExit: queryEl("beta3dFinishExit", "#beta-3d-finish-exit"),
  beta3dRestart: queryEl("beta3dRestart", "#beta-3d-restart"),
  beta3dResults: queryEl("beta3dResults", "#beta-3d-results"),
  beta3dFinalTime: queryEl("beta3dFinalTime", "#beta-3d-final-time"),
  beta3dTime: queryEl("beta3dTime", "#beta-3d-time"),
  beta3dSpeed: queryEl("beta3dSpeed", "#beta-3d-speed"),
  beta3dProgressFill: queryEl("beta3dProgressFill", "#beta-3d-progress-fill"),
  beta3dMarker: queryEl("beta3dMarker", "#beta-3d-marker"),
  hubMapBetaStart: queryEl("hubMapBetaStart", "#hub-map-beta-start"),
  hubMapBetaBack: queryEl("hubMapBetaBack", "#hub-map-beta-back"),
  hubMapBetaCanvas: queryEl("hubMapBetaCanvas", "#hub-map-beta-canvas"),
  hubMapBetaCoords: queryEl("hubMapBetaCoords", "#hub-map-beta-coords"),
  photoCatchBetaStart: queryEl("photoCatchBetaStart", "#photo-catch-beta-start"),
  photoCatchBetaBack: queryEl("photoCatchBetaBack", "#photo-catch-beta-back"),
  photoCatchBetaView: queryEl("photoCatchBetaView", "#photo-catch-beta-view"),
  photoCatchBetaStage: queryEl("photoCatchBetaStage", "#photo-catch-beta-stage"),
  photoCatchBetaVideo: queryEl("photoCatchBetaVideo", "#photo-catch-beta-video"),
  lastGearBetaStart: queryEl("lastGearBetaStart", "#last-gear-beta-start"),
  lastGearSetupPanel: queryEl("lastGearSetupPanel", "#last-gear-setup-panel"),
  lastGearSetupLives: queryEl("lastGearSetupLives", "#last-gear-setup-lives"),
  lastGearSetupOpponents: queryEl("lastGearSetupOpponents", "#last-gear-setup-opponents"),
  lastGearSetupArena: queryEl("lastGearSetupArena", "#last-gear-setup-arena"),
  lastGearSetupSudden: queryEl("lastGearSetupSudden", "#last-gear-setup-sudden"),
  lastGearSetupItems: queryEl("lastGearSetupItems", "#last-gear-setup-items"),
  lastGearSetupAi: queryEl("lastGearSetupAi", "#last-gear-setup-ai"),
  lastGearSetupStart: queryEl("lastGearSetupStart", "#last-gear-setup-start"),
  lastGearBeta: queryEl("lastGearBeta", "#last-gear-beta"),
  lastGearBetaBack: queryEl("lastGearBetaBack", "#last-gear-beta-back"),
  lastGearCanvas: queryEl("lastGearCanvas", "#last-gear-canvas"),
  lastGearSpeed: queryEl("lastGearSpeed", "#last-gear-speed"),
  lastGearNitroFill: queryEl("lastGearNitroFill", "#last-gear-nitro-fill"),
  lastGearStatusGrid: queryEl("lastGearStatusGrid", "#last-gear-status-grid"),
  lastGearItemSlot: queryEl("lastGearItemSlot", "#last-gear-item-slot"),
  lastGearItemIcon: queryEl("lastGearItemIcon", "#last-gear-item-icon"),
  lastGearItemName: queryEl("lastGearItemName", "#last-gear-item-name"),
  lastGearAnnouncer: queryEl("lastGearAnnouncer", "#last-gear-announcer"),
  lastGearAnnouncerEvent: queryEl("lastGearAnnouncerEvent", "#last-gear-announcer-event"),
  lastGearAnnouncerLine: queryEl("lastGearAnnouncerLine", "#last-gear-announcer-line"),
  lastGearResults: queryEl("lastGearResults", "#last-gear-results"),
  lastGearResultTitle: queryEl("lastGearResultTitle", "#last-gear-result-title"),
  lastGearResultCopy: queryEl("lastGearResultCopy", "#last-gear-result-copy"),
  lastGearRestart: queryEl("lastGearRestart", "#last-gear-restart"),
  lastGearFinishExit: queryEl("lastGearFinishExit", "#last-gear-finish-exit"),
  betaTrackSelect: queryEl("betaTrackSelect", "#beta-track-select"),
  betaTrackList: queryEl("betaTrackList", "#beta-track-list"),
  betaTrackPreview: queryEl("betaTrackPreview", "#beta-track-preview"),
  betaTrackStart: queryEl("betaTrackStart", "#beta-track-start"),
  betaTrackBack: queryEl("betaTrackBack", "#beta-track-back"),
  betaLoading: queryEl("betaLoading", "#beta-loading"),
  betaExit: queryEl("betaExit", "#beta-exit"),
  betaFinishExit: queryEl("betaFinishExit", "#beta-finish-exit"),
  betaRestart: queryEl("betaRestart", "#beta-restart"),
  betaDebug: queryEl("betaDebug", "#beta-debug"),
  betaCanvas: queryEl("betaCanvas", "#beta-canvas"),
  betaMinimap: queryEl("betaMinimap", "#beta-minimap"),
  betaTime: queryEl("betaTime", "#beta-time"),
  betaLap: queryEl("betaLap", "#beta-lap"),
  betaCheckpoint: queryEl("betaCheckpoint", "#beta-checkpoint"),
  betaSpeed: queryEl("betaSpeed", "#beta-speed"),
  betaPosition: queryEl("betaPosition", "#beta-position"),
  betaItemSlot: queryEl("betaItemSlot", "#beta-item-slot"),
  betaItemIcon: queryEl("betaItemIcon", "#beta-item-icon"),
  betaItemName: queryEl("betaItemName", "#beta-item-name"),
  betaItemPrompt: queryEl("betaItemPrompt", "#beta-item-prompt"),
  betaCountdown: queryEl("betaCountdown", "#beta-countdown"),
  betaResults: queryEl("betaResults", "#beta-results"),
  betaFinalTime: queryEl("betaFinalTime", "#beta-final-time"),
  garageLoadoutsOpen: queryEl("garageLoadoutsOpen", "#garage-loadouts-open"),
  builderMenu: queryEl("builderMenu", "#builder-menu"),
  builderEditor: queryEl("builderEditor", "#builder-editor"),
  builderLoadPanel: queryEl("builderLoadPanel", "#builder-load-panel"),
  builderNew: queryEl("builderNew", "#builder-new"),
  builderLoad: queryEl("builderLoad", "#builder-load"),
  builderMenuNote: queryEl("builderMenuNote", "#builder-menu-note"),
  builderPalette: queryEl("builderPalette", "#builder-palette"),
  builderGrid: queryEl("builderGrid", "#builder-grid"),
  builderCurrentName: queryEl("builderCurrentName", "#builder-current-name"),
  builderDirtyState: queryEl("builderDirtyState", "#builder-dirty-state"),
  builderBuild: queryEl("builderBuild", "#builder-build"),
  builderRotate: queryEl("builderRotate", "#builder-rotate"),
  builderClear: queryEl("builderClear", "#builder-clear"),
  builderSave: queryEl("builderSave", "#builder-save"),
  builderExit: queryEl("builderExit", "#builder-exit"),
  builderLoadBack: queryEl("builderLoadBack", "#builder-load-back"),
  builderTrackList: queryEl("builderTrackList", "#builder-track-list"),
  deleteTracks: queryEl("deleteTracks", "#delete-tracks"),
  builderModal: queryEl("builderModal", "#builder-modal"),
  builderModalTitle: queryEl("builderModalTitle", "#builder-modal-title"),
  builderModalCopy: queryEl("builderModalCopy", "#builder-modal-copy"),
  builderModalSubcopy: queryEl("builderModalSubcopy", "#builder-modal-subcopy"),
  builderModalInput: queryEl("builderModalInput", "#builder-modal-input"),
  builderModalActions: queryEl("builderModalActions", "#builder-modal-actions"),
  storyCityMap: queryEl("storyCityMap", "#story-city-map"),
  tunerRankBadge: queryEl("tunerRankBadge", "#tuner-rank-badge"),
  tunerRankOpen: queryEl("tunerRankOpen", "#tuner-rank-open"),
  tunerRankList: queryEl("tunerRankList", "#tuner-rank-list"),
  tunerRankBack: queryEl("tunerRankBack", "#tuner-rank-back"),
  convoyEntryNode: queryEl("convoyEntryNode", "#convoy-entry-node"),
  convoyButtons: queryEl("convoyButtons", "#convoy-buttons"),
  storyFactionBadge: queryEl("storyFactionBadge", "#story-faction-badge"),
  storyFactionBadgeImg: queryEl("storyFactionBadgeImg", "#story-faction-badge-img"),
  convoyTitle: queryEl("convoyTitle", "#convoy-title"),
  convoyStageList: queryEl("convoyStageList", "#convoy-stage-list"),
  convoyBack: queryEl("convoyBack", "#convoy-back"),
  convoyLoadoutsOpen: queryEl("convoyLoadoutsOpen", "#convoy-loadouts-open"),
  convoyLoadoutsView: queryEl("convoyLoadoutsView", "#convoy-loadouts-view"),
  convoyLoadoutSlots: queryEl("convoyLoadoutSlots", "#convoy-loadout-slots"),
  convoyLoadoutsBack: queryEl("convoyLoadoutsBack", "#convoy-loadouts-back"),
  storyCitySelect: queryEl("storyCitySelect", "#story-city-select"),
  changeStoryCar: queryEl("changeStoryCar", "#change-story-car"),
  storyCityIcon: queryEl("storyCityIcon", "#story-city-icon"),
  storyCityTitle: queryEl("storyCityTitle", "#story-city-title"),
  storyCitySelect: queryEl("storyCitySelect", "#story-city-select"),
  bossUnlockNote: queryEl("bossUnlockNote", "#boss-unlock-note"),
  storyMapStage: queryEl("storyMapStage", "#story-map-stage"),
  storyPreviewPanel: queryEl("storyPreviewPanel", "#story-preview-panel"),
  closeStoryPreview: queryEl("closeStoryPreview", "#close-story-preview"),
  storyPreviewIcon: queryEl("storyPreviewIcon", "#story-preview-icon"),
  storyPreviewArt: queryEl("storyPreviewArt", "#story-preview-art"),
  storyPreviewLeaderboard: queryEl("storyPreviewLeaderboard", "#story-preview-leaderboard"),
  storyCitySelectPanel: queryEl("storyCitySelectPanel", "#story-city-select-panel"),
  closeCitySelect: queryEl("closeCitySelect", "#close-city-select"),
  storyCityGrid: queryEl("storyCityGrid", "#story-city-grid"),
  campaignType: queryEl("campaignType", "#campaign-type"),
  campaignTitle: queryEl("campaignTitle", "#campaign-title"),
  campaignMeta: queryEl("campaignMeta", "#campaign-meta"),
  campaignRewards: queryEl("campaignRewards", "#campaign-rewards"),
  storyLoadout: queryEl("storyLoadout", "#story-loadout"),
  startCampaign: queryEl("startCampaign", "#start-campaign"),
  changeStoryCar: queryEl("changeStoryCar", "#change-story-car"),
  campaignRaceMount: queryEl("campaignRaceMount", "#campaign-race-mount"),
  vindexList: queryEl("vindexList", "#vindex-list"),
  vindexArt: queryEl("vindexArt", "#vindex-art"),
  vindexNumber: queryEl("vindexNumber", "#vindex-number"),
  vindexName: queryEl("vindexName", "#vindex-name"),
  vindexLine: queryEl("vindexLine", "#vindex-line"),
  vindexStatus: queryEl("vindexStatus", "#vindex-status"),
  vindexClassStamp: queryEl("vindexClassStamp", "#vindex-class-stamp"),
  vindexTypeStamp: queryEl("vindexTypeStamp", "#vindex-type-stamp"),
  vindexPlate: queryEl("vindexPlate", "#vindex-plate"),
  vindexMedallionTracks: queryEl("vindexMedallionTracks", "#vindex-medallion-tracks"),
  vindexFilterButtons: queryEl("vindexFilterButtons", "#vindex-filter-buttons"),
  vindexProgress: queryEl("vindexProgress", "#vindex-progress"),
  vindexMemoriesButton: queryEl("vindexMemoriesButton", "#vindex-memories-button"),
  vindexMemoriesPanel: queryEl("vindexMemoriesPanel", "#vindex-memories-panel"),
  bondSceneModal: queryEl("bondSceneModal", "#bond-scene-modal"),
  bondScenePortrait: queryEl("bondScenePortrait", "#bond-scene-portrait"),
  bondSceneTitle: queryEl("bondSceneTitle", "#bond-scene-title"),
  bondSceneText: queryEl("bondSceneText", "#bond-scene-text"),
  bondSceneContinue: queryEl("bondSceneContinue", "#bond-scene-continue"),
  honkModal: queryEl("honkModal", "#honk-modal"),
  honkModalClose: queryEl("honkModalClose", "#honk-modal-close"),
  honkOptions: queryEl("honkOptions", "#honk-options"),
  honkSubtitle: queryEl("honkSubtitle", "#honk-subtitle"),
  carPickerModal: queryEl("carPickerModal", "#car-picker-modal"),
  carPickerClose: queryEl("carPickerClose", "#car-picker-close"),
  carPickerSearch: queryEl("carPickerSearch", "#car-picker-search"),
  carPickerFilters: queryEl("carPickerFilters", "#car-picker-filters"),
  carPickerSort: queryEl("carPickerSort", "#car-picker-sort"),
  carPickerGrid: queryEl("carPickerGrid", "#car-picker-grid"),
  carPickerSummary: queryEl("carPickerSummary", "#car-picker-summary"),
  carPickerConfirm: queryEl("carPickerConfirm", "#car-picker-confirm"),
  profileList: queryEl("profileList", "#profile-list"),
  profileArt: queryEl("profileArt", "#profile-art"),
  profileCarArt: queryEl("profileCarArt", "#profile-car-art"),
  profileName: queryEl("profileName", "#profile-name"),
  profileMeta: queryEl("profileMeta", "#profile-meta"),
  profileBio: queryEl("profileBio", "#profile-bio"),
  achievementList: queryEl("achievementList", "#achievement-list"),
  achievementDetail: queryEl("achievementDetail", "#achievement-detail"),
  playerPreviewArt: queryEl("playerPreviewArt", "#player-preview-art"),
  playerPreviewName: queryEl("playerPreviewName", "#player-preview-name"),
  playerPreviewMeta: queryEl("playerPreviewMeta", "#player-preview-meta"),
  distanceOptions: queryEl("distanceOptions", "#distance-options"),
  opponentList: queryEl("opponentList", "#opponent-list"),
  opponentPreviewArt: queryEl("opponentPreviewArt", "#opponent-preview-art"),
  opponentPreviewName: queryEl("opponentPreviewName", "#opponent-preview-name"),
  opponentPreviewMeta: queryEl("opponentPreviewMeta", "#opponent-preview-meta"),
  startRace: queryEl("startRace", "#start-race"),
  dragTrack: document.querySelector(".track"),
  dragMapStart: queryEl("dragMapStart", "#drag-map-start"),
  dragCountdown: queryEl("dragCountdown", "#drag-countdown"),
  exportSave: queryEl("exportSave", "#export-save"),
  importSave: queryEl("importSave", "#import-save"),
  saveTransferModal: queryEl("saveTransferModal", "#save-transfer-modal"),
  saveTransferTitle: queryEl("saveTransferTitle", "#save-transfer-title"),
  saveTransferCopy: queryEl("saveTransferCopy", "#save-transfer-copy"),
  saveTransferText: queryEl("saveTransferText", "#save-transfer-text"),
  saveTransferCopyBtn: queryEl("saveTransferCopyBtn", "#save-transfer-copy-btn"),
  saveTransferImportBtn: queryEl("saveTransferImportBtn", "#save-transfer-import-btn"),
  saveTransferClose: queryEl("saveTransferClose", "#save-transfer-close"),
  dailyGoals: queryEl("dailyGoals", "#daily-goals"),
  godMode: queryEl("godMode", "#god-mode"),
  godModal: queryEl("godModal", "#god-modal"),
  godCode: queryEl("godCode", "#god-code"),
  godCodeError: queryEl("godCodeError", "#god-code-error"),
  godCheatStatus: queryEl("godCheatStatus", "#god-cheat-status"),
  confirmGod: queryEl("confirmGod", "#confirm-god"),
  cancelGod: queryEl("cancelGod", "#cancel-god"),
  gasEmptyModal: queryEl("gasEmptyModal", "#gas-empty-modal"),
  gasEmptyCost: queryEl("gasEmptyCost", "#gas-empty-cost"),
  gasEmptyHave: queryEl("gasEmptyHave", "#gas-empty-have"),
  gasNextGallon: queryEl("gasNextGallon", "#gas-next-gallon"),
  gasFullTank: queryEl("gasFullTank", "#gas-full-tank"),
  gasPurchase: queryEl("gasPurchase", "#gas-purchase"),
  gasEmptyCancel: queryEl("gasEmptyCancel", "#gas-empty-cancel"),
  upgradeModal: queryEl("upgradeModal", "#upgrade-modal"),
  closeUpgrade: queryEl("closeUpgrade", "#close-upgrade"),
  confirmUpgrade: queryEl("confirmUpgrade", "#confirm-upgrade"),
  upgradeArt: queryEl("upgradeArt", "#upgrade-art"),
  upgradeSproxTotal: queryEl("upgradeSproxTotal", "#upgrade-sprox-total"),
  upgradeTitle: queryEl("upgradeTitle", "#upgrade-title"),
  upgradeCarName: queryEl("upgradeCarName", "#upgrade-car-name"),
  upgradeCarMeta: queryEl("upgradeCarMeta", "#upgrade-car-meta"),
  upgradeStats: queryEl("upgradeStats", "#upgrade-stats"),
  upgradePartSlots: queryEl("upgradePartSlots", "#upgrade-part-slots"),
  upgradeCost: queryEl("upgradeCost", "#upgrade-cost"),
  openInventory: queryEl("openInventory", "#open-inventory"),
  inventoryModal: queryEl("inventoryModal", "#inventory-modal"),
  closeInventory: queryEl("closeInventory", "#close-inventory"),
  partsGrid: queryEl("partsGrid", "#parts-grid"),
  partDetail: queryEl("partDetail", "#part-detail"),
  equipPartModal: queryEl("equipPartModal", "#equip-part-modal"),
  closeEquipPart: queryEl("closeEquipPart", "#close-equip-part"),
  equipPartsGrid: queryEl("equipPartsGrid", "#equip-parts-grid"),
  equipPartDetail: queryEl("equipPartDetail", "#equip-part-detail"),
  confirmEquipPart: queryEl("confirmEquipPart", "#confirm-equip-part"),
  unequipPart: queryEl("unequipPart", "#unequip-part"),
  replacePart: queryEl("replacePart", "#replace-part"),
  resetProgress: queryEl("resetProgress", "#reset-progress"),
  replayTutorial: queryEl("replayTutorial", "#replay-tutorial"),
  tutorialReplayModal: queryEl("tutorialReplayModal", "#tutorial-replay-modal"),
  tutorialReplayYes: queryEl("tutorialReplayYes", "#tutorial-replay-yes"),
  tutorialSceneSelect: queryEl("tutorialSceneSelect", "#tutorial-scene-select"),
  tutorialReplayCancel: queryEl("tutorialReplayCancel", "#tutorial-replay-cancel"),
  tutorialSceneOptions: queryEl("tutorialSceneOptions", "#tutorial-scene-options"),
  tutorialFirstModal: queryEl("tutorialFirstModal", "#tutorial-first-modal"),
  tutorialFirstYes: queryEl("tutorialFirstYes", "#tutorial-first-yes"),
  tutorialFirstNo: queryEl("tutorialFirstNo", "#tutorial-first-no"),
  cityUnlockModal: queryEl("cityUnlockModal", "#city-unlock-modal"),
  cityUnlockIcon: queryEl("cityUnlockIcon", "#city-unlock-icon"),
  cityUnlockTitle: queryEl("cityUnlockTitle", "#city-unlock-title"),
  cityUnlockClose: queryEl("cityUnlockClose", "#city-unlock-close"),
  pinkSlipWarningModal: queryEl("pinkSlipWarningModal", "#pink-slip-warning-modal"),
  pinkSlipWarningCopy: queryEl("pinkSlipWarningCopy", "#pink-slip-warning-copy"),
  confirmPinkSlipRisk: queryEl("confirmPinkSlipRisk", "#confirm-pink-slip-risk"),
  cancelPinkSlipRisk: queryEl("cancelPinkSlipRisk", "#cancel-pink-slip-risk"),
  resetModal: queryEl("resetModal", "#reset-modal"),
  confirmReset: queryEl("confirmReset", "#confirm-reset"),
  cancelReset: queryEl("cancelReset", "#cancel-reset"),
  mph: queryEl("mph", "#mph"),
  gear: queryEl("gear", "#gear"),
  distance: queryEl("distance", "#distance"),
  shiftReadout: queryEl("shiftReadout", "#shift-readout"),
  perfectStreak: queryEl("perfectStreak", "#perfect-streak"),
  tachFill: queryEl("tachFill", "#tach-fill"),
  playerRacer: queryEl("playerRacer", "#player-racer"),
  playerRacerImage: queryEl("playerRacerImage", "#player-racer-image"),
  rivalRacer: queryEl("rivalRacer", "#rival-racer"),
  rivalRacerImage: queryEl("rivalRacerImage", "#rival-racer-image"),
  raceMessage: queryEl("raceMessage", "#race-message"),
  shiftButton: queryEl("shiftButton", "#shift-button"),
  dragOpponentCount: queryEl("dragOpponentCount", "#drag-opponent-count"),
  dragLaneUp: queryEl("dragLaneUp", "#drag-lane-up"),
  dragLaneDown: queryEl("dragLaneDown", "#drag-lane-down"),
  gearshiftIndicator: queryEl("gearshiftIndicator", "#gearshift-indicator"),
  dragLaunchLights: queryEl("dragLaunchLights", "#drag-launch-lights"),
  launchPhaseLabel: queryEl("launchPhaseLabel", "#launch-phase-label"),
  dragExtraOpponents: queryEl("dragExtraOpponents", "#drag-extra-opponents"),
  rivalDragLane: queryEl("rivalDragLane", "#rival-drag-lane"),
  playerDragLane: queryEl("playerDragLane", "#player-drag-lane"),
  nitroFill: queryEl("nitroFill", "#nitro-fill"),
  nitroReadout: queryEl("nitroReadout", "#nitro-readout"),
  nitroButton: queryEl("nitroButton", "#nitro-button"),
  garageGrid: queryEl("garageGrid", "#garage-grid"),
  garageStatus: queryEl("garageStatus", "#garage-status"),
  difficulty: queryEl("difficulty", "#difficulty"),
  volume: queryEl("volume", "#volume"),
  screenEffects: queryEl("screenEffects", "#screen-effects"),
  haptics: queryEl("haptics", "#haptics"),
  highVisCues: queryEl("highVisCues", "#high-vis-cues"),
  reducedMotion: queryEl("reducedMotion", "#reduced-motion"),
  shiftKey: queryEl("shiftKey", "#shift-key"),
  nitroKey: queryEl("nitroKey", "#nitro-key"),
  verticalUpKey: queryEl("verticalUpKey", "#vertical-up-key"),
  verticalDownKey: queryEl("verticalDownKey", "#vertical-down-key"),
  verticalLeftKey: queryEl("verticalLeftKey", "#vertical-left-key"),
  verticalRightKey: queryEl("verticalRightKey", "#vertical-right-key"),
  evolutionModal: queryEl("evolutionModal", "#evolution-modal"),
  forgePanel: queryEl("forgePanel", "#forge-panel"),
  forgeCardTitle: queryEl("forgeCardTitle", "#forge-card-title"),
  forgeCardSubtitle: queryEl("forgeCardSubtitle", "#forge-card-subtitle"),
  forgeKicker: queryEl("forgeKicker", "#forge-kicker"),
  forgeTitle: queryEl("forgeTitle", "#forge-title"),
  forgeSubtitle: queryEl("forgeSubtitle", "#forge-subtitle"),
  forgeModeToggle: queryEl("forgeModeToggle", "#forge-mode-toggle"),
  garageContent: queryEl("garageContent", "#garage-content"),
  forgeVatImg: queryEl("forgeVatImg", "#forge-vat-img"),
  forgeMedallionGrid: queryEl("forgeMedallionGrid", "#forge-medallion-grid"),
  forgeInventoryPanel: queryEl("forgeInventoryPanel", "#forge-inventory-panel"),
  forgeAnimationArea: queryEl("forgeAnimationArea", "#forge-animation-area"),
  forgeSelectedName: queryEl("forgeSelectedName", "#forge-selected-name"),
  forgeSelectedMedallion: queryEl("forgeSelectedMedallion", "#forge-selected-medallion"),
  forgeUnlockBtn: queryEl("forgeUnlockBtn", "#forge-unlock-btn"),
  forgeUnlockedPopup: queryEl("forgeUnlockedPopup", "#forge-unlocked-popup"),
  devTestHome: queryEl("devTestHome", "#dev-test-home"),
  devTestSounds: queryEl("devTestSounds", "#dev-test-sounds"),
  devTestAnimations: queryEl("devTestAnimations", "#dev-test-animations"),
  devTestScenes: queryEl("devTestScenes", "#dev-test-scenes"),
  devTestScenePlayer: queryEl("devTestScenePlayer", "#dev-test-scene-player"),
  devTestSoundSelect: queryEl("devTestSoundSelect", "#dev-test-sound-select"),
  devTestSoundPlay: queryEl("devTestSoundPlay", "#dev-test-sound-play"),
  devTestSoundStop: queryEl("devTestSoundStop", "#dev-test-sound-stop"),
  devTestHonkSelect: queryEl("devTestHonkSelect", "#dev-test-honk-select"),
  devTestHonkEmotion: queryEl("devTestHonkEmotion", "#dev-test-honk-emotion"),
  devTestHonkPlay: queryEl("devTestHonkPlay", "#dev-test-honk-play"),
  devTestHonkStop: queryEl("devTestHonkStop", "#dev-test-honk-stop"),
  devTestForgeMedallion: queryEl("devTestForgeMedallion", "#dev-test-forge-medallion"),
  devTestForgePlay: queryEl("devTestForgePlay", "#dev-test-forge-play"),
  devTestSpindellMedallion: queryEl("devTestSpindellMedallion", "#dev-test-spindell-medallion"),
  devTestSpindellPlay: queryEl("devTestSpindellPlay", "#dev-test-spindell-play"),
  devTestCharacterRow: queryEl("devTestCharacterRow", "#dev-test-character-row"),
  devTestSceneNav: queryEl("devTestSceneNav", "#dev-test-scene-nav"),
  devTestSceneList: queryEl("devTestSceneList", "#dev-test-scene-list"),
  devTestSceneCode: queryEl("devTestSceneCode", "#dev-test-scene-code"),
  devTestSceneTitle: queryEl("devTestSceneTitle", "#dev-test-scene-title"),
  devTestScenePortrait: queryEl("devTestScenePortrait", "#dev-test-scene-portrait"),
  devTestSceneSpeaker: queryEl("devTestSceneSpeaker", "#dev-test-scene-speaker"),
  devTestSceneText: queryEl("devTestSceneText", "#dev-test-scene-text"),
  devTestScenePrev: queryEl("devTestScenePrev", "#dev-test-scene-prev"),
  devTestSceneNext: queryEl("devTestSceneNext", "#dev-test-scene-next"),
  fusionGambleModal: queryEl("fusionGambleModal", "#fusion-gamble-modal"),
  fusionGambleCopy: queryEl("fusionGambleCopy", "#fusion-gamble-copy"),
  confirmFusionGamble: queryEl("confirmFusionGamble", "#confirm-fusion-gamble"),
  cancelFusionGamble: queryEl("cancelFusionGamble", "#cancel-fusion-gamble"),
  medallionEarnedPopup: queryEl("medallionEarnedPopup", "#medallion-earned-popup"),
  evolutionStage: queryEl("evolutionStage", "#evolution-stage"),
  evolutionKicker: queryEl("evolutionKicker", "#evolution-kicker"),
  evolutionTitle: queryEl("evolutionTitle", "#evolution-title"),
  evolutionCopy: queryEl("evolutionCopy", "#evolution-copy"),
  evolveButton: queryEl("evolveButton", "#evolve-button"),
  closeEvolution: queryEl("closeEvolution", "#close-evolution"),
  evolutionAnimation: queryEl("evolutionAnimation", "#evolution-animation"),
  evolutionAnimationCurrent: queryEl("evolutionAnimationCurrent", "#evolution-animation-current"),
  evolutionAnimationNext: queryEl("evolutionAnimationNext", "#evolution-animation-next"),
  bossModal: queryEl("bossModal", "#boss-modal"),
  bossPortrait: queryEl("bossPortrait", "#boss-portrait"),
  bossModalTitle: queryEl("bossModalTitle", "#boss-modal-title"),
  bossModalKicker: queryEl("bossModalKicker", "#boss-modal-kicker"),
  bossModalCopy: queryEl("bossModalCopy", "#boss-modal-copy"),
  continueBoss: queryEl("continueBoss", "#continue-boss"),
  closeBoss: queryEl("closeBoss", "#close-boss"),
  tunerModal: queryEl("tunerModal", "#tuner-modal"),
  tunerOptions: queryEl("tunerOptions", "#tuner-options"),
  settingsTunerOptions: queryEl("settingsTunerOptions", "#settings-tuner-options"),
  cutsceneModal: queryEl("cutsceneModal", "#cutscene-modal"),
  cutsceneTitle: queryEl("cutsceneTitle", "#cutscene-title"),
  cutsceneLeftArt: queryEl("cutsceneLeftArt", "#cutscene-left-art"),
  cutsceneRightArt: queryEl("cutsceneRightArt", "#cutscene-right-art"),
  cutsceneLeftDialogue: queryEl("cutsceneLeftDialogue", "#cutscene-left-dialogue"),
  cutsceneRightDialogue: queryEl("cutsceneRightDialogue", "#cutscene-right-dialogue"),
  backCutscene: queryEl("backCutscene", "#back-cutscene"),
  continueCutscene: queryEl("continueCutscene", "#continue-cutscene"),
  skipCutscene: queryEl("skipCutscene", "#skip-cutscene"),
  closeCutscene: queryEl("closeCutscene", "#close-cutscene"),
  tutorialOverlay: queryEl("tutorialOverlay", "#tutorial-overlay"),
  tutorialCard: queryEl("tutorialCard", "#tutorial-card"),
  tutorialPortrait: queryEl("tutorialPortrait", "#tutorial-portrait"),
  tutorialKicker: queryEl("tutorialKicker", "#tutorial-kicker"),
  tutorialTitle: queryEl("tutorialTitle", "#tutorial-title"),
  tutorialCopy: queryEl("tutorialCopy", "#tutorial-copy"),
  tutorialChoices: queryEl("tutorialChoices", "#tutorial-choices"),
  tutorialBack: queryEl("tutorialBack", "#tutorial-back"),
  tutorialNext: queryEl("tutorialNext", "#tutorial-next"),
  tutorialSkip: queryEl("tutorialSkip", "#tutorial-skip"),
  tutorialSkipModal: queryEl("tutorialSkipModal", "#tutorial-skip-modal"),
  cancelTutorialSkip: queryEl("cancelTutorialSkip", "#cancel-tutorial-skip"),
  confirmTutorialSkip: queryEl("confirmTutorialSkip", "#confirm-tutorial-skip"),
  unmaskModal: queryEl("unmaskModal", "#unmask-modal"),
  unmaskPortrait: queryEl("unmaskPortrait", "#unmask-portrait"),
  unmaskButton: queryEl("unmaskButton", "#unmask-button"),
  continueUnmask: queryEl("continueUnmask", "#continue-unmask"),
  unmaskCopy: queryEl("unmaskCopy", "#unmask-copy")
};
const embeddedRaceHomes = ["play", "time-trial", "boss", "battle"].map((view) => {
  const node = document.querySelector(`#${view}-view`);
  return { view, node, parent: node.parentNode, next: node.nextSibling };
});
let embeddedCampaignView = null;
let pendingBossRaceStart = null;
let pendingCityUnlock = null;
let pendingCityWelcome = null;
